{{- if and .Values.auditLogCollection.enabled (eq .Values.auditLogCollection.provider "gardener") .Values.auditLogCollection.gardener.seedCluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-log-collector-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auditLogCollector.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-log-collector-role-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auditLogCollector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit-log-collector-role
subjects:
- kind: ServiceAccount
  name: {{ include "auditLogCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
