{{- if and (eq (include "metacollector.shouldDeploy" .) "true") (eq "tls" .Values.visionOne.k8sMetaCollector.grpcAuth.type) }}

{{- $secretName := printf "%s-tls-certificate" (include "k8sMetaCollector.fullname" .) }}
{{- $useExisting := and .Values.useExistingSecrets (eq "true" (.Values.useExistingSecrets.operatorSecrets | toString)) }}
{{- $existingSecret := "" }}
{{- if $useExisting }}
  {{- $existingSecret = lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- end }}

{{- $keyPem := "" }}
{{- $certPem := "" }}
{{- $caCertPem := "" }}

{{- if and $useExisting $existingSecret }}
  {{- /* Use existing certificate data */ -}}
  {{- $keyPem = index $existingSecret.data "key.pem" }}
  {{- $certPem = index $existingSecret.data "cert.pem" }}
  {{- $caCertPem = index $existingSecret.data "ca-cert.pem" }}
{{- else }}
  {{- /* Generate new certificates */ -}}
  {{- $cn := (include "k8sMetaCollector.svc.url" .) }}
  {{- $ca := genCA (printf "%s-ca"  (include "k8sMetaCollector.fullname" .)) (default 3650 (int .Values.visionOne.k8sMetaCollector.grpcAuth.certificate.lifetime)) }}
  {{- $cert := genSignedCert $cn nil (list $cn) (default 3650 (int .Values.visionOne.k8sMetaCollector.grpcAuth.certificate.lifetime)) $ca }}
  {{- $keyPem = $cert.Key | b64enc }}
  {{- $certPem = $cert.Cert | b64enc }}
  {{- $caCertPem = $ca.Cert | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8sMetaCollector.labels" . | nindent 4 }}
type: Opaque
data:
  key.pem: {{ $keyPem | quote }}
  cert.pem: {{ $certPem | quote }}
  ca-cert.pem: {{ $caCertPem | quote }}

{{- end }}
