{{- if and (eq true .Values.visionOne.runtimeSecurity.enabled) (eq true .Values.visionOne.fargateInjector.enabled) }}

{{- $secretName := printf "%s-tls-certificate" (include "fargateInjector.fullname" .) }}
{{- $useExisting := and .Values.useExistingSecrets (eq "true" (.Values.useExistingSecrets.operatorSecrets | toString)) }}
{{- $existingSecret := "" }}
{{- if $useExisting }}
  {{- $existingSecret = lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- end }}

{{- $keyPem := "" }}
{{- $certPem := "" }}
{{- $caCertPem := "" }}
{{- $cn := printf "%s.%s.svc" "trendmicro-fargate-injector" .Release.Namespace }}

{{- if and $useExisting $existingSecret }}
  {{- /* Use existing certificate data */ -}}
  {{- $keyPem = index $existingSecret.data "key.pem" }}
  {{- $certPem = index $existingSecret.data "cert.pem" }}
  {{- $caCertPem = index $existingSecret.data "ca-cert.pem" }}
{{- else }}
  {{- /* Generate new certificates */ -}}
  {{- $ca := genCA (printf "%s-ca" "trendmicro-fargate-injector") (default 3650 (int .Values.visionOne.fargateInjector.certificate.lifetime)) }}
  {{- $cert := genSignedCert (default $cn .Values.visionOne.fargateInjector.certificate.commonName) (default nil .Values.visionOne.fargateInjector.certificate.ipAlternativeNames) (default (list $cn) .Values.visionOne.fargateInjector.certificate.dnsAlternativeNames) (default 3650 (int .Values.visionOne.fargateInjector.certificate.lifetime)) $ca }}
  {{- $keyPem = $cert.Key | b64enc }}
  {{- $certPem = $cert.Cert | b64enc }}
  {{- $caCertPem = $ca.Cert | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fargateInjector.labels" . | nindent 4 }}
type: Opaque
data:
  key.pem: {{ $keyPem | quote }}
  cert.pem: {{ $certPem | quote }}
  ca-cert.pem: {{ $caCertPem | quote }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "fargateInjector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fargateInjector.labels" . | nindent 4 }}
webhooks:
  - name: {{ default $cn .Values.visionOne.fargateInjector.certificate.commonName }}
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations: ["CREATE", "CONNECT"]
        resources:
          - "pods"
          - "pods/exec"
          - "pods/attach"
          - "replicasets"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "jobs"
          - "cronjobs"
        scope: "*"
    failurePolicy: {{ required "A valid failure policy is required!" .Values.visionOne.fargateInjector.failurePolicy }}
    clientConfig:
      service:
        name: trendmicro-fargate-injector
        namespace: {{ .Release.Namespace }}
        path: "/"
      caBundle: {{ $caCertPem | quote }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: {{ default 30 .Values.visionOne.fargateInjector.webhookTimeoutSeconds }}

{{- end }}
