{{- include "validateClusterInput" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendmicro-policy-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "policyOperator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/auth: {{ include "container.security.auth.secret" . | sha256sum }}
{{- with (default .Values.podAnnotations.defaults .Values.podAnnotations.policyOperator) }}
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "policyOperator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "policyOperator.serviceAccountName" . }}
{{- $securityContextEnabled := .Values.securityContext.enabled }}
{{- $securityContext := default .Values.securityContext.default .Values.securityContext.policyOperator }}
{{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
{{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container.policyOperator }}
{{- if $securityContextEnabled }}
      securityContext:
{{ toYaml $podSecurityContext | indent 8 }}
{{- end }}
      {{- $imageDefaults := .Values.images.defaults }}
      {{- with .Values.images.policyOperator }}
      {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
      {{- if not (eq "" $secret) }}
      imagePullSecrets:
        - name: {{ $secret | quote }}
      {{- end }}
      containers:
      - name: trendmicro-policy-operator
{{- if $securityContextEnabled }}
        securityContext:
{{ toYaml $containerSecurityContext | indent 12 }}
{{- end }}
        {{- $project := (default $imageDefaults.project .project) }}
        {{- $repository := (ternary (required ".repository is required!" .repository)
          (printf "%s/%s" $project (required ".repository is required!" .repository))
          (not $project))
        }}
        {{- $tag := (default $imageDefaults.tag .tag) }}
        image: {{ include "image.source" (dict "repository" $repository "registry" .registry "tag" $tag "imageDefaults" $imageDefaults "digest" .digest) }}
        imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
        {{- end }}
        args:
        - --zap-devel={{ default "false" .Values.logConfig.devel }}
        - --zap-log-level={{ include "logLevel" (list .Values.visionOne.policyOperator.logLevel .) }}
        - --zap-encoder={{ default "json" .Values.logConfig.encoder }}
        - --zap-stacktrace-level={{ default "error" .Values.logConfig.stacktraceLevel }}
        - --zap-time-encoding={{ default "rfc3339" .Values.logConfig.timeEncoding }}
        - --vision-one-endpoint={{ include "container.security.endpoint" . }}
        - --exclude-kubernetes-service-host-from-proxy={{ default "false" .Values.proxy.excludeKubernetesServiceHost }}
        - --reconciliation-period={{ .Values.visionOne.policyOperator.reconciliationPeriod }}
        - --cluster-policy-name={{ .Values.visionOne.policyOperator.clusterPolicyName }}
        - --cluster-name={{ .Values.visionOne.clusterName }}
        - --cluster-name-prefix={{ .Values.visionOne.clusterNamePrefix }}
        - --cluster-policy-id={{ .Values.visionOne.policyId }}
        - --cluster-group-id={{ .Values.visionOne.groupId }}
        - --namespace={{ .Release.Namespace }}
        - --auth-name={{ template "container.security.fullname" . }}-auth
        - --auto-register={{ default "false" .Values.visionOne.clusterRegistrationKey }}
        - --enable-runtime-mitigation={{ default "false" .Values.visionOne.policyOperator.enableRuntimeMitigation }}
        - --policy-service-port={{ .Values.visionOne.policyOperator.servicePort }}
        - --policy-sync-interval={{ .Values.visionOne.policyOperator.policySyncInterval }}
        - --policy-config-name={{ template "container.security.name" . }}-policy-config
        - --runtime-rulesets-config-name={{ template "container.security.name" . }}-runtime-rulesets-config
        - --runtime-rules-config-name={{ template "container.security.name" . }}-runtime-rules-config
        - --runtime-policy-config-name={{ template "container.security.name" . }}-runtime-policy-config
        - --attestors-config-name={{ template "container.security.name" . }}-attestors-config
        - --spc-mode={{ default "false" .Values.spc.enabled }}
        - --enable-experimental-features={{ default "false" .Values.visionOne.experimental.enabled }}
        - --network-policy-label={{ default "trendmicro" .Release.Name }}
        - --name-label={{ template "container.security.name" . }}
        - --instance-label={{ default "trendmicro" .Release.Name }}
        - --admission-control-enabled={{ default "false" .Values.visionOne.admissionController.enabled }}
        - --continuous-oversight-enabled={{ default "false" .Values.visionOne.oversight.enabled }}
        - --compliance-scan-enabled={{ default "false" .Values.visionOne.complianceScan.enabled }}
        - --runtime-security-enabled={{ default "false" .Values.visionOne.runtimeSecurity.enabled }}
        - --vulnerability-scan-enabled={{ default "false" .Values.visionOne.vulnerabilityScanning.enabled }}
        - --malware-scan-enabled={{ default "false" .Values.visionOne.malwareScanning.enabled }}
        - --secret-scan-enabled={{ default "false" .Values.visionOne.secretScanning.enabled }}      
        {{- if gt (int .Values.replicas.policyOperator) 1 }}
        - --leader-elect
        {{- end }}
        command:
        - /app/policy-operator
        env:
        - name: APPLICATION_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "container.security.proxy.env" . | nindent 8 }}
        {{- include "proxy.selfSignedCertificates.env" . | nindent 8}}
        volumeMounts:
        - mountPath: /var/policy-operator
          name: workdir
        - mountPath: /secrets
          name: bootstrap-token
        {{- if .Values.visionOne.clusterRegistrationKey }}
        - mountPath: /reg-secrets
          name: registration-key
        {{- end }}
        {{- include "proxy.selfSignedCertificates.volumeMounts" . | nindent 8 }}
      volumes:
        - name: workdir
          emptyDir:
{{- if not (.Capabilities.APIVersions.Has "oci.oraclecloud.com/v1beta1") }}
            sizeLimit: 50Mi
{{- end }}
        - name: bootstrap-token
          secret:
            secretName: {{ template "container.security.fullname" . }}-bootstrap-token
        {{- if .Values.visionOne.clusterRegistrationKey }}
            optional: true
        - name: registration-key
          secret:
            secretName: {{ template "container.security.fullname" . }}-registration-key
        {{- end }}
        {{- include "proxy.selfSignedCertificates.volumes" . | nindent 8 }}
      terminationGracePeriodSeconds: 10
{{- if or .Values.nodeSelector.defaults .Values.nodeSelector.policyOperator }}
      nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.policyOperator) | indent 8 }}
{{- end }}
{{- if or .Values.tolerations.defaults .Values.tolerations.policyOperator }}
      tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.policyOperator) | indent 8 }}
{{- end }}
{{- if or .Values.affinity.defaults .Values.affinity.policyOperator }}
      affinity:
{{ toYaml (default .Values.affinity.defaults .Values.affinity.policyOperator) | indent 8 }}
{{- end }}
{{- $classname := (default (default "" .Values.priorityClassName.default ) .Values.priorityClassName.policyOperator) }}
{{- if not (eq "" $classname) }}
      priorityClassName: "{{ $classname }}"
{{- end }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: trendmicro-policy-operator-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
spec:
  ports:
  - name: policy-service
    port: {{ .Values.visionOne.policyOperator.servicePort }}
    targetPort: {{ .Values.visionOne.policyOperator.servicePort }}
  selector:
    {{- include "policyOperator.selectorLabels" . | nindent 4 }}

{{ if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "policyOperator.serviceAccountName" . }}
  labels:
    {{- include "policyOperator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.policyOperator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
