{{- if and .Values.securityContextConstraints.create (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: |
      This SCC provides least-privilege requirement to run Trend Micro Vision One Container Security in Openshift.
  name: {{ template "container.security.name" . }}-default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container.security.labels" . | nindent 4 }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedUnsafeSysctls: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
priority: 0
readOnlyRootFilesystem: true
requiredDropCapabilities: []
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{ .Release.Namespace }}:default
{{ if .Values.serviceAccount.create }}
{{- if eq true .Values.visionOne.admissionController.enabled }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "admissionController.serviceAccountName" . }}
{{- end }}
{{- if eq true .Values.visionOne.oversight.enabled }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "oversight.serviceAccountName" . }}
{{- end }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "usage.serviceAccountName" . }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "workloadOperator.serviceAccountName" . }}
{{- if (or (eq true .Values.visionOne.vulnerabilityScanning.enabled) (eq true .Values.visionOne.malwareScanning.enabled)) }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "scanManager.serviceAccountName" . }}
{{- end }}
{{- if or (eq true .Values.visionOne.runtimeSecurity.enabled)  (eq true .Values.visionOne.malwareScanning.enabled) (eq true .Values.visionOne.fileIntegrityMonitoring.enabled) }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "k8sMetaCollector.serviceAccountName" . }}
{{- end }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "policyOperator.serviceAccountName" . }}
{{- end }}
volumes:
- configMap
- downwardAPI
- emptyDir
- secret
- projected
{{- end }}
