{{- if and .Values.spc.enabled .Values.spc.encryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "container.security.fullname" . }}-encryption-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container.security.labels" . | nindent 4 }}
    
type: Opaque
data:
  encryptionKey: {{ .Values.spc.encryptionKey | toString | b64enc | quote }}
  createdTime: {{ now | date "2006-01-02T15:04:05Z07:00" | b64enc | quote }}
{{- end }}
